<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Gratuito',
                'slug' => 'gratuito',
                'price' => 0,
                'billing_cycle' => 'monthly',
                'description' => 'Ideal para comecar. Publique os seus primeiros produtos sem custos.',
                'features' => [
                    'Ate 10 produtos',
                    'Ate 3 imagens por produto',
                    'Pagina da loja basica',
                    'Suporte por email',
                    'Listagem no marketplace',
                ],
                'max_products' => 10,
                'max_images_per_product' => 3,
                'max_hero_slides' => 0,
                'priority_support' => false,
                'featured_badge' => false,
                'analytics' => false,
                'custom_domain' => false,
                'has_api' => false,
                'has_pos' => false,
                'is_free' => true,
                'is_active' => true,
                'is_recommended' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'Basico',
                'slug' => 'basico',
                'price' => 5000,
                'billing_cycle' => 'monthly',
                'description' => 'Para lojas em crescimento que precisam de mais visibilidade.',
                'features' => [
                    'Ate 50 produtos',
                    'Ate 5 imagens por produto',
                    '1 slide no hero',
                    'Pagina da loja personalizada',
                    'Suporte por email',
                    'Estatisticas basicas',
                ],
                'max_products' => 50,
                'max_images_per_product' => 5,
                'max_hero_slides' => 1,
                'priority_support' => false,
                'featured_badge' => false,
                'analytics' => true,
                'custom_domain' => false,
                'has_api' => false,
                'has_pos' => false,
                'is_free' => false,
                'is_active' => true,
                'is_recommended' => false,
                'sort_order' => 2,
            ],
            [
                'name' => 'Profissional',
                'slug' => 'profissional',
                'price' => 15000,
                'billing_cycle' => 'monthly',
                'description' => 'O plano mais popular. Tudo o que precisa para vender a serio.',
                'features' => [
                    'Ate 200 produtos',
                    'Ate 8 imagens por produto',
                    '3 slides no hero',
                    'Badge de loja verificada',
                    'Prioridade nos resultados',
                    'Estatisticas avancadas',
                    'Suporte prioritario',
                    'POS Offline',
                ],
                'max_products' => 200,
                'max_images_per_product' => 8,
                'max_hero_slides' => 3,
                'priority_support' => true,
                'featured_badge' => true,
                'analytics' => true,
                'custom_domain' => false,
                'has_api' => false,
                'has_pos' => true,
                'is_free' => false,
                'is_active' => true,
                'is_recommended' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Premium',
                'slug' => 'premium',
                'price' => 35000,
                'billing_cycle' => 'monthly',
                'description' => 'Para marcas estabelecidas que querem o maximo de exposicao.',
                'features' => [
                    'Produtos ilimitados',
                    'Ate 15 imagens por produto',
                    '5 slides no hero',
                    'Badge premium exclusivo',
                    'Destaque na pagina inicial',
                    'Estatisticas completas + relatorios',
                    'Suporte prioritario 24/7',
                    'Dominio personalizado',
                    'API de integracao',
                    'POS Offline',
                ],
                'max_products' => 0,
                'max_images_per_product' => 15,
                'max_hero_slides' => 5,
                'priority_support' => true,
                'featured_badge' => true,
                'analytics' => true,
                'custom_domain' => true,
                'has_api' => true,
                'has_pos' => true,
                'is_free' => false,
                'is_active' => true,
                'is_recommended' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'Empresarial',
                'slug' => 'empresarial',
                'price' => 75000,
                'billing_cycle' => 'monthly',
                'description' => 'Solucao completa para grandes empresas e distribuidores.',
                'features' => [
                    'Tudo do Premium',
                    'Produtos ilimitados',
                    'Imagens ilimitadas',
                    'Slides ilimitados',
                    'API de integracao',
                    'POS Offline',
                    'Gestor de conta dedicado',
                    'Relatorios personalizados',
                    'Multi-utilizadores',
                    'Facturacao personalizada',
                ],
                'max_products' => 0,
                'max_images_per_product' => 50,
                'max_hero_slides' => 0,
                'priority_support' => true,
                'featured_badge' => true,
                'analytics' => true,
                'custom_domain' => true,
                'has_api' => true,
                'has_pos' => true,
                'is_free' => false,
                'is_active' => true,
                'is_recommended' => false,
                'sort_order' => 5,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
