<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Database\Seeder;

class SubcategorySeeder extends Seeder
{
    public function run(): void
    {
        $map = [
            'electronica' => [
                'Smartphones',
                'Tablets',
                'Televisores',
                'Cameras Fotograficas',
                'Auscultadores & Colunas',
                'Smartwatches',
                'Acessorios Electronicos',
                'Carregadores & Cabos',
                'Drones',
                'Projectores',
            ],
            'moda-feminina' => [
                'Vestidos',
                'Saias',
                'Blusas & Tops',
                'Calcas',
                'Sapatos Femininos',
                'Sandálias',
                'Bolsas & Carteiras',
                'Joias & Bijuteria',
                'Roupa Interior',
                'Capulanas & Tecidos',
                'Oculos de Sol',
                'Relogios Femininos',
            ],
            'moda-masculina' => [
                'Camisas',
                'T-Shirts',
                'Calcas & Jeans',
                'Fatos & Blazers',
                'Sapatos Masculinos',
                'Tenis & Sapatilhas',
                'Relogios Masculinos',
                'Cintos & Carteiras',
                'Roupa Interior Masculina',
                'Bones & Chapeus',
                'Oculos de Sol',
            ],
            'casa-decoracao' => [
                'Moveis Sala',
                'Moveis Quarto',
                'Moveis Cozinha',
                'Iluminacao',
                'Tapetes & Cortinas',
                'Roupa de Cama',
                'Utensilios de Cozinha',
                'Electrodomesticos',
                'Decoracao & Quadros',
                'Jardim & Exterior',
                'Organizacao & Arrumacao',
                'Casa de Banho',
            ],
            'automoveis-motas' => [
                'Carros Usados',
                'Carros Novos',
                'Motas & Scooters',
                'Pecas & Acessorios Auto',
                'Pneus & Jantes',
                'Oleos & Lubrificantes',
                'Audio & GPS Auto',
                'Ferramentas Auto',
                'Bicicletas',
                'Capacetes & Proteccao',
            ],
            'beleza-cuidados' => [
                'Maquilhagem',
                'Cuidados com a Pele',
                'Cuidados com o Cabelo',
                'Perfumes Femininos',
                'Perfumes Masculinos',
                'Unhas & Manicure',
                'Barbear & Grooming',
                'Produtos Capilares',
                'Cremes & Locoes',
                'Kits de Beleza',
            ],
            'desporto-lazer' => [
                'Futebol',
                'Basquetebol',
                'Fitness & Musculacao',
                'Corrida & Atletismo',
                'Natacao',
                'Artes Marciais',
                'Roupa Desportiva',
                'Calcado Desportivo',
                'Camping & Ar Livre',
                'Ciclismo',
                'Yoga & Pilates',
            ],
            'alimentacao-bebidas' => [
                'Mercearia & Basicos',
                'Frutas & Legumes',
                'Carnes & Peixe',
                'Laticinios & Ovos',
                'Padaria & Pastelaria',
                'Bebidas & Sumos',
                'Conservas & Enlatados',
                'Temperos & Molhos',
                'Congelados',
                'Snacks & Doces',
                'Produtos Importados',
                'Bebidas Alcoolicas',
            ],
            'livros-papelaria' => [
                'Livros Escolares',
                'Livros de Ficcao',
                'Livros Tecnicos',
                'Livros Infantis',
                'Cadernos & Blocos',
                'Material Escolar',
                'Canetas & Lapis',
                'Impressao & Copia',
                'Biblias & Religiosos',
                'Revistas & Jornais',
            ],
            'bebes-criancas' => [
                'Fraldas & Higiene',
                'Alimentacao Bebe',
                'Roupa de Bebe',
                'Roupa de Crianca',
                'Brinquedos',
                'Carrinhos & Cadeiras',
                'Bercos & Camas',
                'Sapatos de Crianca',
                'Material Escolar Infantil',
                'Seguranca & Proteccao',
            ],
            'saude-bem-estar' => [
                'Suplementos Alimentares',
                'Vitaminas & Minerais',
                'Equipamento Medico',
                'Primeiros Socorros',
                'Cuidados Pessoais',
                'Produtos Naturais',
                'Proteccao Solar',
                'Higiene Oral',
                'Preservativos & Intimos',
                'Mascaras & Proteccao',
            ],
            'ferramentas-construcao' => [
                'Ferramentas Manuais',
                'Ferramentas Electricas',
                'Material de Construcao',
                'Tintas & Vernizes',
                'Canalizacao',
                'Electricidade',
                'Portas & Janelas',
                'Cimento & Argamassa',
                'Seguranca Trabalho',
                'Geradores & Energia Solar',
            ],
            'informatica' => [
                'Computadores Portateis',
                'Computadores Desktop',
                'Monitores',
                'Impressoras & Scanners',
                'Teclados & Ratos',
                'Discos & Armazenamento',
                'Redes & Wi-Fi',
                'Software & Licencas',
                'Componentes PC',
                'Acessorios Informatica',
            ],
            'jogos-consolas' => [
                'PlayStation',
                'Xbox',
                'Nintendo',
                'Jogos PC',
                'Acessorios Gaming',
                'Cadeiras Gaming',
                'Jogos de Tabuleiro',
                'Jogos de Cartas',
                'Realidade Virtual',
                'Comandos & Controladores',
            ],
            'animais' => [
                'Racao & Alimentacao',
                'Acessorios Caes',
                'Acessorios Gatos',
                'Aquarios & Peixes',
                'Aves & Gaiolas',
                'Higiene & Saude Animal',
                'Camas & Transporte',
                'Brinquedos Animais',
                'Coleiras & Trelas',
                'Veterinaria',
            ],
            'musica-instrumentos' => [
                'Guitarras',
                'Teclados & Pianos',
                'Baterias & Percussao',
                'Instrumentos de Sopro',
                'Equipamento de Som',
                'Microfones',
                'Mesas de Mistura',
                'Acessorios Musicais',
                'Cordas & Palhetas',
                'Estudio & Gravacao',
            ],
            'escritorio-material' => [
                'Mesas & Secretarias',
                'Cadeiras de Escritorio',
                'Arquivos & Armarios',
                'Material de Escritorio',
                'Agendas & Planners',
                'Quadros Brancos',
                'Calculadoras',
                'Telefones Fixos',
                'Destruidoras de Papel',
                'Apresentacao & Conferencia',
            ],
            'servicos' => [
                'Reparacao Electronica',
                'Servicos Domesticos',
                'Transporte & Mudancas',
                'Aulas & Explicacoes',
                'Design & Marketing',
                'Fotografia & Video',
                'Contabilidade & Finanças',
                'Eventos & Festas',
                'Saude & Bem-estar',
                'Tecnologia & Informatica',
            ],
            'imoveis' => [
                'Apartamentos Venda',
                'Apartamentos Arrendamento',
                'Moradias Venda',
                'Moradias Arrendamento',
                'Terrenos',
                'Escritorios & Lojas',
                'Armazens',
                'Quintas & Fazendas',
                'Quartos',
                'Garagens & Estacionamento',
            ],
            'agricultura' => [
                'Sementes & Mudas',
                'Fertilizantes & Adubos',
                'Ferramentas Agricolas',
                'Irrigacao',
                'Pecuaria',
                'Avicultura',
                'Produtos Fitossanitarios',
                'Maquinaria Agricola',
                'Racao Animal',
                'Colheita & Armazenamento',
            ],
        ];

        foreach ($map as $categorySlug => $subcategories) {
            $category = Category::where('slug', $categorySlug)->first();
            if (!$category) continue;

            foreach ($subcategories as $name) {
                $slug = \Illuminate\Support\Str::slug($name);
                Subcategory::updateOrCreate(
                    ['category_id' => $category->id, 'slug' => $slug],
                    ['name' => $name]
                );
            }
        }
    }
}
